<?php

/**
 * calculates the fence length when user inputs posts and railings.
 * @param $POST_input ARRAY $_POST array generated by user input.
 * @return STRING string containing the fence length.
 */
function fence_calculator($POST_input)
{
    if (!is_array($POST_input)) {
        return 'Input is not an array';
    } else {
        $railings = $POST_input['railings'] - 1;
        $posts = $POST_input['posts'] - 2;
        if ($railings < 0 || $posts < 0) {
            $error = 'Invalid input - a fence must have at least 2 posts and 1 railing.';
            return $error;
        } else {
            $fence_length = 1.7;
            $railings *= 1.5;
            $posts *= 0.1;
            $fence_length += $railings + $posts;
            return 'This fence would be ' . $fence_length . ' metres long.';
        }
    }
}

/**
 * calculates the posts and railings quantity when user inputs fence length.
 * @param $POST_input ARRAY $_POST array generated by user input.
 * @return STRING string containing the posts and railings quantity.
 */
function pandr_calculator($POST_input)
{
    if (!is_array($POST_input)) {
        return 'Input is not an array';
    } else {
        $length = $POST_input['fence_length'] - 1.7;
        if ($length < 0) {
            $error = 'Invalid input - fence length must be greater than 1.7m (2 posts and 1 railing.)';
            return $error;
        } else {
            $railings = 1;
            $posts = 2;
            if (round($length / 1.5) === $length / 1.5) {
                $railings += $length / 1.5;
            } elseif (round($length / 1.5) < $length / 1.5) {
                $railings += round($length / 1.5) + 1;
            } else {
                $railings += round($length / 1.5);
            }
            if ($railings > 1) {
                return 'This fence length would require ' . $posts . ' posts and ' . $railings . ' railings.';
            } else {
                return 'This fence length would require ' . $posts . ' posts and ' . $railings . ' railing.';
            }
        }
    }
}

if ($_POST['choice'] === 'fence') {
    echo fence_calculator($_POST);
} elseif ($_POST['choice'] === 'posts/railing') {
    echo pandr_calculator($_POST);
} else {
    echo 'Must select calculator type.';
}
?>
